M48
; DRILL file {KiCad 9.0.2-2.fc42} date 2025-07-11T00:06:05+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-11T00:06:05+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-2.fc42
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X151.993Y-46.825
X157.772Y-46.825
T2
X137.243Y-110.58
X171.582Y-110.58
M30
